name: sncf_ticket_storage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^3.5.6
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  barcode_widget: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
